pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }
    
    environment {
       
        cluster = 'vproappproduction'
        service = 'vprod'

    }

    stages {
       stage('Deploy to prod ecs') {
           steps {
               withAWS(credentials: "awscreds", region: "eu-north-1") {
                   sh '''
                   aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment
                   '''
               }
           }
       }
    }
    
    post{
        always {
            echo 'Slack Notification'
            slackSend (channel: '#jenkinscicd', message: "Build ${currentBuild.fullDisplayName} finished with status: ${currentBuild.currentResult}")
        }
    }
}