pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }
    
    environment {
        SNAP_REPO = 'vprofile-snapshot'
		NEXUS_USER = 'admin'
		NEXUS_PASS = '2002'
		RELEASE_REPO = 'vprofile-release'
		CENTRAL_REPO = 'vpro-maven-central'
		NEXUSIP = '172.31.29.120'
		NEXUSPORT = '8081'
		NEXUS_GRP_REPO = 'vpro-maven-group'
        NEXUS_LOGIN = 'nexuslogin'
        SONARSERVER ='sonarserver'
        SONARSCANNER = 'sonarscanner'
        registryCredential = 'ecr:eu-north-1:awscreds'
        appRegistry = '837553126503.dkr.ecr.eu-north-1.amazonaws.com/vprofileappimg'
        vprofileRegistry = 'https://837553126503.dkr.ecr.eu-north-1.amazonaws.com'
    }

    stages {
        stage('Build'){
            steps {
                sh 'mvn -s settings.xml -DskipTests install'
            }
            post {
                success {
                    echo ' Now archiving artifacts.'
                    archiveArtifacts artifacts: '**/*.war'
                }
                failure {
                    echo 'Build failed.'
                }
            }
        }

        stage('Test') {
            steps {
                sh 'mvn -s settings.xml test'
            }
            post {
                success {
                    echo 'Test completed successfully.'
                }
                failure {
                    echo 'Test failed.'
                }
            }
        }
        stage('Checkstyle analysis'){
            steps {
                sh 'mvn -s settings.xml checkstyle:checkstyle'
            }
        }

        stage('Sonar Analysis') {
            environment {
                scannerHome = tool "${SONARSCANNER}"
            }
            steps {
                withSonarQubeEnv("${SONARSERVER}") {
                    sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                    -Dsonar.projectName=vprofile \
                    -Dsonar.projectVersion=1.0 \
                    -Dsonar.sources=src/ \
                    -Dsonar.java.binaries=target/test-classes/com/visualpathit/ \
                    -Dsonar.junit.reportsPath=target/surefire-reports/ \
                    -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                    -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                }
            }
        }
        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        stage('Upload Artifact to Nexus') {
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: "${NEXUSIP}:${NEXUSPORT}",
                    groupId: 'QA',
                    version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                    repository: "${RELEASE_REPO}",
                    credentialsId: "${NEXUS_LOGIN}",
                    artifacts: [
                        [artifactId: 'vproapp',
                         classifier: '',
                         file: 'target/vprofile-v2.war',
                         type: 'war']
                    ]
                )
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    // Add Jenkins user to docker group if not already added
                    sh 'if ! groups jenkins | grep -q docker; then sudo usermod -aG docker jenkins; fi'
                    // Reload permissions
                    sh 'sudo chmod 666 /var/run/docker.sock'
                    dockerImage = docker.build("${appRegistry}:${BUILD_NUMBER}", "Docker-files/app/multi-stage/")
                }
            }
        }
        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry("${vprofileRegistry}", "${registryCredential}") {
                        dockerImage.push("${BUILD_NUMBER}")
                        dockerImage.push("latest")
                    }
                }
            }
        }
    }
    
    post{
        always {
            echo 'Slack Notification'
            slackSend (channel: '#jenkinscicd', message: "Build ${currentBuild.fullDisplayName} finished with status: ${currentBuild.currentResult}")
        }
    }
}